mutation ($customerInput: CustomerInput!) {
  customerUpdate(input: $customerInput) {
    customer {
      id
      firstName
      lastName
    }
    userErrors {
      field
      message
    }
  }
}
